### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by roman-bodavskiy** [gKrokod/botReborn#1]
Привет, Алексей! Меня зовут Роман, я буду проводить ревью кода.
Наченем с простого, стиль кода

1.  Излишние и самоочевидные комментарии типа этого `-- implementation console verion`. Закомментированный код. Комментарии нужны только для нетипичных участков кода, там где логика работы до конца не понятна из него самого, из названия функций и т д.
2. опечатки в коде и комментариях `verion`, `unknwon` и др
3. использование `camelCase`: в конфигах `helpmenu`, `repeatmenu` и др

**Comment by gKrokod** [comment]
Добрый день! Спасибо! После исправления замечаний, как Вам сообщить об этом?

**Comment by roman-bodavskiy** [comment]
После исправления замечаний нужно создать пулл реквест (один на все замечания, либо на каждое замечание свой пулл реквест) и сообщить мне или Свете в телеграм. У нас принято общаться на ты)

**Comment by roman-bodavskiy** [comment]
На будущее, в задании есть такое условие:

> 15. Все изменения в проект в процессе код-ревью вносите через пулл-реквесты. В ПР указывайте ссылку на ишью.

**Comment by gKrokod** [comment]
Светлана дала следующие указания: "Требования к работе над правками:
! Правку надо исправлять везде, где она встречается, а не только там где указал ревьювер.
 Нужно для каждой правки создавать отдельный коммит с указанием номера ишью. Чтобы связать ишью с конкретным коммитом нужно указать в имени коммита #номер_ишью. Как пример - "Change double quotes to single quotes #12". (Строгое соблюдения отдельного коммита для каждой правки не обязательно)."
 Возможно я доделаю данные через коммиты, а следующие сделаю через пулл-реквесты? Или откатить текущие и сразу оформить пулл-реквестами?

**Comment by roman-bodavskiy** [comment]
> Возможно я доделаю данные через коммиты, а следующие сделаю через пулл-реквесты? Или откатить текущие и сразу оформить пулл-реквестами?

ну сделай пожалуйста реверт и пулл реквесты (один или несколько, как удобней), а то замердженный код не очень удобно проверять

**Comment by roman-bodavskiy** [comment]
тут есть два способа
```
git revert <commit hash>
git reset <commit hash>
```
тебе можно использовать любой,но при работе в команде используется только первый, так как нельзя менять коммиты в ветке `main`, над которой могут работать другие разработчики

**Comment by gKrokod** [comment]
Через реверт не удалось слить с другой веткой (коммиты одинаковые), сделал через reset и новую ветку. В следующий раз проще будет сразу через новую ветку.

**Comment by olgaklimenko** [comment]
Могу посоветовать экстеншен для проверки опечаток (увидела в ишью этот пункт). Если пользуешься `vscode`, можно установить `streetsidesoftware.code-spell-checker`. Для других ide тоже можно найти аналоги. Мне помогло больше не получать дискашены по поводу опечаток :)
