### ISSUE TITLE
Проверка работоспособности

### ISSUE THREAD

**Issue by roman-bodavskiy** [gKrokod/botReborn#11]
Консольный бот работает нормально
В телеграм боте почему-то не отрабатывают кнопки, подвисают, и количество повторов не изменяется.  После этого и другие сообщения не отрабатывают, он опять присылает кнопки
Можешь проверить?
<img src="https://github.com/user-attachments/assets/3ab0cb09-a5c0-4785-8b81-35c4f5ecc374" width="300">   <img src="https://github.com/user-attachments/assets/1e112868-736d-4a63-a8c4-51777694ec4a" width="300">

**Comment by gKrokod** [comment]
Проверил. Работает. Сделал клон репозитория и запустил по инструкции. Прошу проверить еще раз.
