### ISSUE TITLE
Ошибка пользователя

### ISSUE THREAD

**Issue by olgaklimenko** [gKrokod/botReborn#15]
В текущей реализации функции `ChangeRepeatCountForUser`, если происходит ошибка, она просто логируется, но пользователь не получает никаких оповещений. Это приводит к следующим проблемам:

- Если пользователь вводит неверное значение, он не понимает, что пошло не так, и попадает обратно в цикл, передавая ошибочные данные снова.

- В случае других ошибок пользователь также остаётся в неведении, что вызывает неудобства, потраченные нервы и может заставить пользователя подумать, что бот сломан.

Предлагаю добавить оповещения для пользователя. Если пользователь вводит невалидные данные, бот должен сообщить, какой формат ожидается (например, "Пожалуйста, введите число от 1 до 5"). Если произошла другая непредвиденная ошибка (не тот формат сообщения, и пользователь это не контролирует), бот должен отправить сообщение вида "Произошла ошибка, мы уже работаем над её решением."

**Comment by gKrokod** [comment]
Привет! Поскольку это не было описано в ТЗ, то и не было реализовано. Можешь уточнить, что происходит после оповещения об ошибке пользователя? Он снова ожидает ввод числа повторов или должен перейти в основной цикл (до ввода команды /repeat)?

**Comment by olgaklimenko** [comment]
Привет :)
Давай тогда этот пункт будет носить рекомендательный характер, сам смотри, добавлять или нет)

Бот ожидает числа для команды repeat, и если пользователь вводит что-то неожиданное, бот сообщает ему об ошибке. Чтобы изменить число повторов, пользователь может снова вызвать команду /repeat. Можно даже добавить в текст ошибки что-то вроде: 'Неправильное значение. Попробуйте снова: /repeat', чтоы пользователь понимал что дальше делать:)
