### ISSUE TITLE
logMessage

### ISSUE THREAD

**Issue by olgaklimenko** [gKrokod/botReborn#16]
`Handlers.Logger.logMessage` принимает первым параметром `logHandle`, который инициализируется при старте приложения и при каждом вызове функции логирования он одинаковый. Предлагаю оптимизировать код, передав `logHandle` в `logMessage` один раз на уровне инициализации.

**Comment by gKrokod** [comment]
Понял. Подумаю, как сделать. А это не противоречит самому духу архитектуры handle pattern, когда можно в любом месте изменить поведение подменив функции, например, на запись в файл?

**Comment by olgaklimenko** [comment]
Я поняла, что ты имеешь в виду, но думаю, это не противоречит `handle pattern`. Гибкость для изменения поведения, к которой мы стремимся, используя хэндл паттерн, сохранится, даже если `logHandle` передавать один раз на уровне инициализации. Если понадобится изменить его (например, начать логировать в файл), это можно сделать через конфигурацию или при повторной инициализации, а не через передачу в каждый вызов функции.

Логгер обычно задается для всей системы в зависимости от окружения, где запущен проект. Если бы `logHandle` у тебя в проекте действительно менялся для разных функций (хотя, думаю, это не очень частый кейс в реальности), тогда такой подход мог бы иметь смысл. Но в данном случае, думаю, оптимизация оправдана.

**Comment by olgaklimenko** [comment]
Могу предложить интуитивный лайфхак, который чаще всего срабатывает (как минимум должен быть маркером того, чтобы посмотреть, можно ли отрефакторить код). Если в сигнатуре функции ты видишь постоянно повторяющийся аргумент, который связан с вещами, которые настраиваются один раз при старте проекта (например, конфиги, логгеры или что-то зависящее от окружения), то велика вероятность, что этот параметр не нужно тащить через весь код. Вместо этого можно частично применить функцию на уровне инициализации или положить его в Reader, чтобы избавить код от излишней передачи параметров.

**Comment by gKrokod** [comment]
У меня не получилось просто передалать таким образом код. Я даже сделал службу логирования через отдельный поток (как описано в книге "Параллельное и конкуретное программирования на языке Haskell"), но и там всплывают потом проблемы того же толка.  Поэтому:
1. Вы можете показать код, как это правильно сделать в данном случае?
2. Прислушаться к авторитету и оставить, как было сделано. Саймон Марлоу пишет [стр. 169 ru, p.130 eng] об этой идее так :

> "Абстрактный тип данных Logger представляет дескриптор службы журнализации, новая служба создается функцией initLogger. Дескриптор необходим для выполнения операции журнализации - хорошей практикой является наличие соответсвующего значения, которое можно передавать по назначению, - это лучше, чем глобально определенный идентификатор верхнего уровня, потому что можно, к примеру, иметь несколько таких служб"

**Comment by olgaklimenko** [comment]
В отдельный поток не нужно конечно, это слишком.
Хорошо, пусть остаётся, но хочется тогда разных применений сразу, например для вызова из бота пишем в файл лог, для консольного вызова в в терминал, но этого нет в задании. Пусть будет заложено на потом, ничего плохого в этом нет )

**Comment by olgaklimenko** [comment]
ВОт это я имела ввиду для логера, и не понятно почему оно в итоге может не работать. При этом никто не мешает хэндлеры разные подставлять в logMessage для разных клиентов и сервисов. Для этого в хэндлерах сервисов вместо хэндла для логгера сделать функцию которая принимает этот хэндл.

![image](https://github.com/user-attachments/assets/26973663-b07f-4045-9ef9-6a603e02dd7a)

**Comment by gKrokod** [comment]
Я правильно понял, что:

1. Мы теперь расширяем интерфейс каждого отдельного блока вручную, вместо того, чтобы передать туда обработчик для работы с логами? И если он изменится, то надо будем его менять во всех блоках, а не в одном месте?
2. Нам все равно придется передавать в функцию Handlers.Base.logMessage собственный Handle. Итоговое количество аргументов не изменится. Было три, осталось три. В чем выгода?

**Comment by olgaklimenko** [comment]
1. Да, так и есть. Поэтому если хотим оставить простое масштабирование, можно оставить как есть. Поэтому ишью я закрыла).
2. Собственный handle это какой? logHandle в коде будет 1 раз передаваться вот при инициализации каждого хэндла. Потом logMessage можно будет вызывать без передачи logHandle.
```
data Handle m = Handle
  { base :: Handlers.Base.Handle m,
    client :: Handlers.Client.Handle m,
    helpMessage :: T.Text,
    repeatMessage :: T.Text,
    logMessage ::  Log -> String -> m ()  - тут нет теперь аргумента logHandle
  }
```

**Comment by olgaklimenko** [comment]
Кстати вот сейчас пишу комменты и вместо "тут нет теперь аргумента logHandle" хочется написать тип хэндлера логера, а он называется просто Handle и надо смотреть на его путь, чтобы было понятно какой хэндл имеется ввиду. Если бы сразу назвал его LogHandle, можно было бы легче понимать о чем речь (и тут всех хэндлеров это касается, у них у всех тип одинаково называется)

**Comment by gKrokod** [comment]
- А я и не знал, что их нужно по разному называл. Думал это одни из фич подхода, называть все Handle.
- Вот что я имел ввиду про аргументы. Чтобы собрать проект с новым подходом нужно дописать (миниум для Base):
```
Initialization.hs

  let baseHandle =             
        Handlers.Base.Handle   
          { Handlers.Base.defaultRepeatCount = RepeatCount $ cRepeatCount cfg, 
            Handlers.Base.readStackMessage = Base.readStackMessage stackMessage,
            Handlers.Base.saveMessage = Base.saveMessage stackMessage,
            Handlers.Base.eraseMessage = Base.eraseMessage stackMessage, 
            Handlers.Base.findUser = Base.findUser base,
            Handlers.Base.updateUser = Base.updateUser base,
            Handlers.Base.logMessage = Handlers.Logger.logMessage logHandle,
            Handlers.Base.logger = logHandle
          }      
```              

```
Handlers/Base.hs
import Data.Text (Text)
          
data Handle m = Handle
  { defaultRepeatCount :: RepeatCount,
    readStackMessage :: m (Maybe Message, Maybe LastMessage),
    saveMessage :: Message -> m (),
    eraseMessage :: Message -> m (),
    findUser :: User -> m (Maybe RepeatCount), 
    updateUser :: User -> RepeatCount -> m (),
    logMessage :: Log -> Text -> m (),
    logger :: Handlers.Logger.Handle m 
  } 
```
Как теперь выполняется логирование в модуле `Handlers/Base.hs`, например, в функции
```
giveRepeatCountFromBase :: (Monad m) => Handle m -> User -> m RepeatCount
giveRepeatCountFromBase h user = do
```

По старому варианту: `Handlers.Logger.logMessage logHandle Debug "Base. The user not found in the database"`
По новому варианту:     ` logMessage h Debug "Base. Save the user in the database`

**Comment by olgaklimenko** [comment]
- Опыт именования потом придет) Мы не вычеркиваем слово "Handle" из названия типа, мы просто уточняем его название. Так как ты сделал - тоже рабочий вариант, но когда всё построено на хэндл паттерне лучше заложить их различие в названии. Все равно у них функционал отличается, и хэндл для бд имеет совершенно отличающиеся функции от тех, что в хэндле логгера. Можно это отличие заложить в названии. Еще, если вдруг займёшься переименованиями, название `Base` плохое для функционала бд, потому что выглядит по названию, как будто этот модуль должен содержать какой-то базовый функционал. В идеале его нужно переименовать в `Database`, или `DB`, или что-то подобное.

- Это немножко другое, потому что вложенность теперь одна. У тебя же до этого есть строчка еще, где ты хэндл логгера достаёшь из основного хэндла. Плюс можно экстеншен `RecordWildCards` добавить, тогда вообще не надо будет вручную указывать хэндлер и код значительно уменьшается:

![image](https://github.com/user-attachments/assets/154cc752-59e4-4646-a6e8-0e36f131ccac)

Вроде такой экстеншен не запрещён, жалко не прописали это в заданиях, добавлю этот пункт.

**Comment by olgaklimenko** [comment]
Ещё у меня возникают сомнения по поводу логера в каждом хэндле. Вот, к примеру, запускаем мы бот с хэндлером "пиши лог в файл", и клиент для консоли с хэндлером "пиши лог в консоль".  Но ведь тогда мы ожидаем, что для бота и логи по бд тоже будут в файле, а для консоли в консоли? Сейчас такое работать не будет, потому что мы при инициализации в хэндлер бд зашиваем конкретный логер.
