### ISSUE TITLE
Улучшение инкапсуляции ClientTM

### ISSUE THREAD

**Issue by olgaklimenko** [gKrokod/botReborn#17]
Отлично сделано, что бот работает с телеграммом через интерфейсы `fetch` и `carryAway` и не дергает запросы http и парсинг напрямую.

Есть предложение полностью инкапсулировать логику взаимодействия с API Telegram - бот будет импортировать только `fetch`, `carryAway` из сервиса `ClientTM`, а внутренние детали останутся скрытыми внутри модуля. И переместить `ClientTM.hs` в его директорию, чтобы он лежал вместе со своим сервисом.

**Comment by gKrokod** [comment]
В этом случае надо ли создавать отдельную папку `ClientConsole` и переносить туда `ClientConsole.hs `дополнительно? Для единобразия?

**Comment by gKrokod** [comment]
Так только две функции и возможно импортировать из модуля клиента телеграмм `module ClientTM (fetch, carryAway) where`. Разве так и не сделано? Остается только вопрос о переносе `ClientTM.hs` в папку `ClientTM`.

**Comment by olgaklimenko** [comment]
Да, дело в переносе файла `ClientTM.hs` в папку `ClientTM`. 
Помимо переноса файла, можно сделать дополнительно вот что:
Разнести `Fetch` и `CarryAway` по разным модулям, они будут считаться внутренними модулями. А в `ClientTM` оставить только публиный интрефейс: экспортировать только те функции, которые нужны боту (`fetch` и `carryAway`), при этом инкапсулируя детали работы с API Telegram.

**Comment by olgaklimenko** [comment]
Для `ClientConsole` да, можно сделать аналогично. Я бы клиентов в загнала в одну директорию `Clients`: 

Clients/
├── Console.hs
├── Telegram.hs
├── Console/
│   └── Internal/
│       ├── CarryAway.hs
│       └── Fetch.hs
└── Telegram/
    └── Internal/
        ├── CarryAway.hs
        ├── Fetch.hs
        ├── HttpMessage.hs
        └── Parse.hs

Всё что в `Internal` - внутренняя логика по работе с клиентом, а `Telegram.hs` и `Console.hs` экспортируют функции, которые можно использовать вне этого клиента. И если рука потянется импортировать в основной код что-то, что должно быть скрыто за интерфейсом, `Internal` в пути до модуля насторожит и заставит поискать интерфейс для работы с этим.

**Comment by olgaklimenko** [comment]
Это только 1 пример, как можно огранизовать структуру. Подсмотреть такие вещи можно на больших проектах, где работают команды и код все время меняется и масштабируется (можно просто поискать на гитхае опен сорс проекты). В проекте на одного человека это может быть не так критично, так что можно просто перенести `ClientTM` из основного кода.
